services:
  web:
    build: .
    ports:
      - "80:80"
    volumes:
      - .:/var/www
      - ./public:/var/www/html
    depends_on:
      - mysql
    env_file:
      - .env
    environment:
      MYSQL_HOST: mysql # Define MYSQL_HOST como 'mysql' dentro do contêiner 'web'

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./sql:/docker-entrypoint-initdb.d
    env_file:
      - .env

volumes:
  db_data: